DROP TABLE OSSZEKESZIT;
DROP TABLE MEGRENDELES;
DROP TABLE TORZSVASARLO;
DROP TABLE TERMEK;
DROP TABLE VELEMENY;
DROP TABLE FELHASZNALO;
DROP TABLE LETREHOZ;
DROP TABLE RGAZDA;
DROP TABLE ELADO;
DROP TABLE KATEGORIA;


create table KATEGORIA(
  Kategoria VARCHAR(23) PRIMARY KEY NOT NULL
);

create table ELADO(
 FelhaszNev VARCHAR(20) PRIMARY KEY NOT NULL,
 Jelszo VARCHAR(21) NOT NULL
);

create table RGAZDA(
 FelhaNev VARCHAR(29) PRIMARY KEY NOT NULL,
 Jelszo VARCHAR(21) NOT NULL
);

create table LETREHOZ(
 FelhaNev VARCHAR(29) NOT NULL,
 FOREIGN KEY(FelhaNev) REFERENCES RGAZDA(FELHANEV),
 FelhaszNev VARCHAR(20) NOT NULL,
 FOREIGN KEY(FelhaszNev) REFERENCES ELADO(FELHASZNEV)
);

create table FELHASZNALO(
 FelhNev VARCHAR(29) PRIMARY KEY NOT NULL,
 Jelszo VARCHAR(21) NOT NULL,
 Nev CHAR(31) NOT NULL,
 Lakcim VARCHAR(50),
 SzulDatum DATE,
 Email VARCHAR(40)
);

create table VELEMENY(
 Ertekeles NUMBER(2) PRIMARY KEY,
 FelhNev VARCHAR(29),
 FOREIGN KEY(FelhNev) REFERENCES FELHASZNALO(FELHNEV)
);

create table TERMEK(
  TermekKod NUMBER(20) NOT NULL,
  ar NUMBER(10) NOT NULL,
  nev VARCHAR2(30) NOT NULL,
  Leiras VARCHAR(102),
  Ertekeles NUMBER(2),
  DarabSzam Number(5),
  Kategoria VARCHAR(23),
  FOREIGN KEY(Kategoria) REFERENCES KATEGORIA(KATEGORIA),
  FOREIGN KEY(Ertekeles) REFERENCES VELEMENY(ERTEKELES),
  PRIMARY KEY(TermekKod)
);

create table TORZSVASARLO(
 FelhNev VARCHAR(29),
 TorzsvE NUMBER(1) PRIMARY KEY NOT NULL,
 FOREIGN KEY(FelhNev) REFERENCES FELHASZNALO(FELHNEV)
);

create table MEGRENDELES(
 Azon NUMBER(9) PRIMARY KEY NOT NULL,
 FelhNev VARCHAR(29),
 Idopont DATE NOT NULL,
 Osszeg NUMBER(11) NOT NULL,
 TorzsvE NUMBER(1),
 FOREIGN KEY(FelhNev) REFERENCES FELHASZNALO(FELHNEV),
 FOREIGN KEY(TorzsvE) REFERENCES TORZSVASARLO(TORZSVE)
);

create table OSSZEKESZIT(
 FelhaszNev VARCHAR(20) NOT NULL,
 Azon NUMBER(9) NOT NULL,
 FOREIGN KEY(FelhaszNev) REFERENCES ELADO(FELHASZNEV),
 FOREIGN KEY(Azon) REFERENCES MEGRENDeLES(AZON)
);

create table RENDEL(
 TermekKod NUMBER(20) NOT NULL,
 FOREIGN KEY(TermekKod) REFERENCES TERMEK(TERMEKKOD),
 Azon NUMBER(9),
 FOREIGN KEY(Azon) REFERENCES MEGRENDELES(AZON)
);

-- adatbázist feltöltő adatok --

INSERT INTO ELADO VALUES('BALAZS','ASDFG');
INSERT INTO ELADO VALUES('cica','cica');
INSERT INTO ELADO VALUES('ASD','ASD');
INSERT INTO ELADO VALUES('BALAZS','ASDFG');
INSERT INTO ELADO VALUES('ELADO','ASD');
INSERT INTO ELADO VALUES('Valcsika','igen');
INSERT INTO ELADO VALUES('Vali','nem');
INSERT INTO ELADO VALUES('Warwick','lol');
INSERT INTO ELADO VALUES('NEM','ztu');
INSERT INTO ELADO VALUES('Hello','dfr');
INSERT INTO ELADO VALUES('Adatb','cbv');
INSERT INTO ELADO VALUES('Fanni','dfd');
INSERT INTO ELADO VALUES('ASD','ASD');
INSERT INTO KATEGORIA VALUES('PÉKÁRÚ');
INSERT INTO KATEGORIA VALUES('NŐI RUHÁZAT');
INSERT INTO KATEGORIA VALUES('FÉRFI RUHÁZAT');
INSERT INTO KATEGORIA VALUES('GYERMEK RUHÁZAT');
INSERT INTO KATEGORIA VALUES('TEJTERMÉKEK');
INSERT INTO KATEGORIA VALUES('KERT');
INSERT INTO KATEGORIA VALUES('ALKOHOLOS ITALOK');
INSERT INTO KATEGORIA VALUES('ITALOK');
INSERT INTO KATEGORIA VALUES('HÚSOK');
INSERT INTO KATEGORIA VALUES('Édesség');
INSERT INTO termek VALUES('987654321','500','csoki','mogyoróvajas szelet','','100','Édesség');
INSERT INTO RGAZDA VALUES('GAZDA1','NEMJELSZO345');
INSERT INTO FELHASZNALO VALUES('BALAZS','ASDFG','Ficzere Balazs','2134 CSICSERI UTCA 45.',TO_DATE('2000 04 25', 'yyyy mm dd'), 'balazsvagyokhelloszia@gmail.com');
INSERT INTO FELHASZNALO VALUES('ANYU','ARDFG','Bohus Reka', '3400 NEMECSEK UTCA 3.', TO_DATE('1950 03 02', 'yyyy mm dd'), 'anyunakhivj@gmail.com');


