INSERT INTO ELADO VALUES('BALAZS','ASDFG');
INSERT INTO ELADO VALUES('ELADO','ASD');
INSERT INTO ELADO VALUES('Valcsika','igen');
INSERT INTO ELADO VALUES('Vali','nem');
INSERT INTO ELADO VALUES('Warwick','lol');
INSERT INTO ELADO VALUES('NEM','ztu');
INSERT INTO ELADO VALUES('Hello','dfr');
INSERT INTO ELADO VALUES('Adatb','cbv');
INSERT INTO ELADO VALUES('Fanni','dfd');
INSERT INTO ELADO VALUES('ASD','ASD');
INSERT INTO KATEGORIA VALUES('PÉKÁRÚ');
INSERT INTO KATEGORIA VALUES('NŐI RUHÁZAT');
INSERT INTO KATEGORIA VALUES('FÉRFI RUHÁZAT');
INSERT INTO KATEGORIA VALUES('GYERMEK RUHÁZAT');
INSERT INTO KATEGORIA VALUES('TEJTERMÉKEK');
INSERT INTO KATEGORIA VALUES('KERT');
INSERT INTO KATEGORIA VALUES('ALKOHOLOS ITALOK');
INSERT INTO KATEGORIA VALUES('ITALOK');
INSERT INTO KATEGORIA VALUES('HÚSOK');
INSERT INTO RGAZDA VALUES('GAZDA','NEMJELSZO345');
INSERT INTO FELHASZNALO VALUES('BALAZS','ASDFG','2134 CSICSERI UTCA 45.', '2000.04.25', 'balazsvagyokhelloszia@gmail.com');
INSERT INTO FELHASZNALO VALUES('ANYU','ARDFG', '3400 NEMECSEK UTCA 3.' '1960.03.02', 'anyunakhivj@gmail.com');


