
CREATE OR REPLACE TRIGGER megrendel
AFTER INSERT OR UPDATE ON Rendel
FOR EACH ROW    
BEGIN
  UPDATE MEGRENDELES.OSSZEG
  SET MEGRENDELES.OSSZEG = MEGRENDELES.OSSZEG + (AR * DARAB)
  WHERE FELHNEV = MEGRENDELES.FELHNEV;
END megrendel;
/